### ISSUE TITLE
upload the models to another site

### ISSUE THREAD

**Issue by ABDOELSHEMY** [linchuming/ImageSR-Tensorflow#1]
Hi @linchuming 
thankes for sharing your work, unfortunately i failed to download your models from pan.baidu.com, could you please reupload it to an easy linke to download from without forcing to install extra software.

**Comment by linchuming** [comment]
@ABDOELSHEMY 
Thanks for your star. I upload the model to Google Drive:
https://drive.google.com/open?id=1IUKH4f0LzkobU4zktA3ZzEg86-ufrV1c
If you want to obtain better performance, you can train the model more steps by yourself. The model is easy to train.
