### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Sabina085** [linchuming/ImageSR-Tensorflow#2]
Hi Chuming Lin,

Could you please add a license to the repo?
I would like to use some of the preprocessing and evaluation code for a research project. 
I will, of course, mention your repository both in my code, in the report and in any publication that may follow. I would also be glad to cite any article of yours which used that repository. Thank you for sharing this code, which has been very useful for my work, on github.

**Comment by linchuming** [comment]
OK. Thank you for your attention to my code.
